name: test-and-build-image
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest 
    env:
      VUE_APP_ROLLOUT_KEY: ${{ secrets.VUE_APP_ROLLOUT_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npm run test:unit

      - name: publish GHA run test results
        uses: cloudbees-io-gha/publish-test-results@v2
        with:
          test-type: junit
          results-path: junit.xml